### ISSUE TITLE
typos in .adl files - missing character

### ISSUE THREAD

**Issue by prjemian** [epics-modules/std#10]
Seems to be a common pattern of typos in some .adl files in stdApp/op/adl:

    grep "hildren {"  *.adl  | grep -v children | sort -u

A leading letter "c" is missing (should be `children`).  Affects these files (in R3-5, at least):

```
beamHistory_full.adl
EMW_PS.adl
ID_taper_ctrl.adl
linkHelpStd.adl
Nano2k_help.adl
Nano2k_more.adl
New_SR_Status.adl
scaler16_full.adl
scaler16_full_calc.adl
scaler_full_calc.adl
sectorStatus.adl
softMotorHelp.adl
```

Similarly:

    grep "han="  *.adl  | grep -v chan | sort -u

also is missing a leading letter "c" (should be `chan`).  These files:

```
beamHistory_full.adl
EMW_PS.adl
ID_taper_ctrl.adl
linkHelpStd.adl
Nano2k_help.adl
Nano2k_more.adl
New_SR_Status.adl
scaler16_full.adl
scaler16_full_calc.adl
scaler_full_calc.adl
sectorStatus.adl
softMotorHelp.adl
```

**Comment by prjemian** [comment]
Since these missing symbols are at the start of a line, MEDM's .adl file structure suggests that there is more missing content.  For example, `children` is always nested in a `composite` and `chan` does not appear at the root level of the .adl file.

**Comment by MarkRivers** [comment]
Those errors appear to have been recently introduced, for example in this commit:
```
corvette:stdApp/op/adl>git log scaler16_full.adl
commit 85ef91440cd4dd9838d745a4e716d20187d3f5de
Author: Tim Mooney <mooney@aps.anl.gov>
Date:   Tue Jul 10 13:56:53 2018 -0500

    Modified for better conversion to caQtDM


corvette:stdApp/op/adl>git diff e5c169825e6adc80d7615115c121ec078d098645  0e875b62734d9ffbe1080ae5b5c0d4dda55684e2 ID_taper_ctrl.adl | grep hildren
+hildren {
-       children {
+hildren {
-       children {

```
I did not have the errors in my working directory until I just did a git pull and got those commits.

**Comment by prjemian** [comment]
Spot checking commit 85ef91440cd4dd9838d745a4e716d20187d3f5de, looks as if the lines beginning with [`han=` and `hildren {`](https://github.com/epics-modules/std/commit/85ef91440cd4dd9838d745a4e716d20187d3f5de#diff-65bb3c67affc350afeaeee1d524dcecbL1013) should have been removed as well.  They are leftover content from the `composite` container that was removed.

**Comment by MarkRivers** [comment]
@timmmooney were those edits done with medm or some other way?  If with medm, does this mean there is a bug in medm?

**Comment by timmmooney** [comment]
I think those edits were done with a python program that intended to move rectangles to the back and ungroup display elements so the result would translate into .ui displays all of whose widgets could be written to.


Tim Mooney (mooney@anl.gov) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________
