### ISSUE TITLE
Epid (using EpidSoft support) does not work if ODEL==0

### ISSUE THREAD

**Issue by ralphlange** [epics-modules/std#12]
A change in c2f4981 introduced a bug in the devSoftEpid Device Support that leads to OVAL never being changed (i.e. controller is disfunctional) when ODEL == 0.

**Comment by ralphlange** [comment]
Fix:
```
Index: stdApp/src/devEpidSoft.c
===================================================================
--- stdApp/src/devEpidSoft.c    (working copy)
+++ stdApp/src/devEpidSoft.c    (working copy)
@@ -207,7 +207,7 @@
     pepid->dt   = dt;
     pepid->err  = e;
     pepid->cval  = cval;
-    if ((pepid->odel != 0) && (fabs(pepid->oval - oval) > pepid->odel)) {
+    if ((pepid->odel == 0) || (fabs(pepid->oval - oval) > pepid->odel)) {
         pepid->oval  = oval;
     }
     pepid->p  = p;
```

**Comment by MarkRivers** [comment]
Thanks for finding this.  Clearly I never tested it after this commit. :-(

**Comment by ralphlange** [comment]
This might even justify a quick bugfix release - @keenanlang?

**Comment by MarkRivers** [comment]
Should be fixed with https://github.com/epics-modules/std/commit/caabd2e941ce93f9a8bab0a393a5bd1a775d22e9

@ralphlange can you test it?

**Comment by ralphlange** [comment]
I did - this change works for the ODEL==0 case.

Note that I did not test the ODEL functionality, for which the documentation seems to be out-of-date, so I can't be 100% sure what the correct behavior is.

**Comment by ralphlange** [comment]
Awwww.
As @jeonghanlee points out in #13: the above fix is fine, the caabd2e commit is not.

**Comment by jeonghanlee** [comment]
@ralphlange , please check the pull request.

**Comment by ralphlange** [comment]
Not fixed by caabd2e, correct.

**Comment by jeonghanlee** [comment]
It was fixed with missing {. At the same time, I was working for ESS std module in order to upgrade the latest version. :)

**Comment by ralphlange** [comment]
I did the same upgrade for CODAC Core System today, that's when I found epid had stopped working. (CCS adds a few tests to verify basic functionality.)
Obviously, I had fixed the issue for the CCS code (see above diff), so I didn't follow the details of merging it upstream.
Issue fixed with merging #13 by 7aabaf1.

@keenanlang: sorry that jump was too short...

**Comment by keenanlang** [comment]
Updated the bugfix release to point to correctly fixed commit.

**Comment by ralphlange** [comment]
Thanks a lot.
Yesterday might not make it into the great book of QA History.

**Comment by MarkRivers** [comment]
I can't believe I did the commit without even typing make!

Lessons learned: 

- Pull requests always help avoid typos.
- All of the epics-modules should be in the APS Jenkins build system (tests Linux, Windows, vxWorks) and have Travis CI for Linux as well.

**Comment by ralphlange** [comment]
Actually, std does have a Travis build with a working badge on the README - none of us checked and saw that it failed. (Pretty pathetic.)

**Comment by ralphlange** [comment]
The epid record being disfunctional since May without anyone noticing is also a bad sign. Of tests missing, in this case.

**Comment by MarkRivers** [comment]
Yes, I realized that there was a Travis failure right after I said we needed to add Travis!
