### ISSUE TITLE
problem with converted caQtDM screen

### ISSUE THREAD

**Issue by prjemian** [epics-modules/std#4]
while setting up caQtDM screens for 7-BM, found this to be a problem:
- /APSshare/epics/synApps_5_8/support/std-3-4/stdApp/op/ui/scaler16_full_calc.ui, macro: P=7bmb1:,S=scaler1
- all Result widgets are white yet PVs exist, such as first one:
  
    jemian@gov .../xorApps/adl $ caget 7bmb1:scaler1_calc1.VAL
    7bmb1:scaler1_calc1.VAL        0

investigate and compare both MEDM and caQtDM

**Comment by keenanlang** [comment]
The PV's connect just fine. The issue is that the background of the result is set to white. The question is whether it should be changed to either black or use the default background.
